# Generated by Django 5.1 on 2024-09-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_profile_education_alter_profile_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='experience',
            field=models.TextField(default=''),
        ),
    ]
