# Generated by Django 5.1 on 2024-09-24 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_profile_address_alter_profile_education_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='title',
        ),
    ]
